server:
  port: 80
spring:
  thymeleaf:
    cache: false
    mode: HTML
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql:///findlover?useSSL=false
      # url: jdbc:mysql://172.17.46.180:3306/findlover?useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-total: 2
      max-wait-millis: 6000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 40MB
  cache:
    type: ehcache
    ehcache:
      config: ehcache.xml
    cache-names: user-cache,dict-cache


# Mybatis config
mybatis:
  type-aliases-package: com.hpe.findlover.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    cache-enabled: true


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

mapper:
  mappers:
    - com.hpe.util.BaseTkMapper
  not-empty: false
  identity: MYSQL

fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList: 192.168.91.132:22122
  # trackerList: 172.17.46.190:22122